version: '3'

services:
  db:
    image: postgres:10.2
    environment:
      - POSTGRES_PASSWORD=johann_gambolputty
      - DB_NAME=development
  web:
    build: .
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=johann_gambolputty
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    links:
      - db
  webpacker:
    build: .
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: bundle exec webpack-dev-server
    volumes:
      - .:/app
    ports:
      - '3035:3035'