version: '3'

services:
  db:
    image: postgres:10.2
    environment:
      - POSTGRES_PASSWORD=johann_gambolputty
      - DB_NAME=development
  web:
    build: .
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=johann_gambolputty
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    links:
      - db