apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}-secret"
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  secret-key-base: {{ randAlphaNum 30 | b64enc | quote }}